name: POINT GARDEN SERVICE

on:
  push:

  jobs:
    build:
      runs-on: Windows-latest
      permissions:
         contents: read
      steps:   
       -uses: actions/checkout@v4
       -name: Set up JDK 17
        uses:chmod +x actions/setup-java@v4
      with:
          java-versions: 17
          distribution: 'temurin'
      -name: Setup Gradle
      uses: gradle/actions/setup-gradle@v9
    -name: Build with Gradle Wrapper
  run:  ./gradlew build
    
dependency-submission:
      run-on: Windows-latest
      permissions:
        contents: write
steps:
    -uses: action/checkout@v4
    -name: Set up JDK 17
uses: actions/setup-java@v4
with:
        java-version: "17"
        distribution: 'temurin
       -name: Generate and submit dependency graph
        uses: gradle/actions/dependancy-submission@v4
        
